### ISSUE TITLE
Validate errors only when submitting or touched

### ISSUE THREAD

**Issue by alexbouchardd** [tannerlinsley/react-form#212] opened 2017-12-18 17:24 UTC
Hello! 
I've ran into the issue where all my fields show error after the user inputs anything in the first one.

I've read this issue https://github.com/react-tools/react-form/issues/190 but I find it quite odd and a burden to implement in each of my forms. I was thinking that support for validating form fields only when touched or on submit should be bake in as in seems like a very common approach to form behavior.

Did I miss something? Thoughts?

**Comment by alexbouchardd** [comment] 2017-12-18 17:26
After further reading I've seen multiple other issues centered around this topic. I understand the argument for validating the whole form on input for some use cases, therefore such behavior could maybe sit behind a flag similarly to `dontValidateOnMount`

**Comment by joepuzzo** [comment] 2017-12-19 01:17
Just use touched and errors to get what you need

**Comment by joepuzzo** [comment] 2017-12-20 15:12
I just added a prop for only validating when submitting. Still thinking about the touched one.

**Comment by mihaiblaga89** [comment] 2017-12-20 15:39
Please add the ```touched``` as well. As far as I remember that's the way v1 worked. Also, it's hard to do validations with fields marked as required. It will trigger the same bug that's described in the first post. 

Right now i'm iterating over values from submitError and validating them one by one(using validate.js). The problem is I can't make them "required" because all of them will be triggered once I fill one. 

The best scenario would be to, let's say you have a form with 3 fields, name, user, pass. Fill first, you get {name: '...'} in values, fill the second, you'll get {name: '...', user: '...'}. But as soon as you click submit, you get all of them, even if they are not filled {name: '...', user: '...', pass: null}. This way you can iterate over keys and do validations properly. Just my 2 cents.

**Comment by joepuzzo** [comment] 2017-12-20 15:51
Im a little confused by your last paragraph above... can you elaborate? you say "Fill first, you get {name: '...'} in values, fill the second, you'll get {name: '...', user: '...'}. But as soon as you click submit, you get all of them, even if they are not filled {name: '...', user: '...', pass: null}." are the first two things in that sentence are referring to the values and the last the errors? And i cant change the core format of the sync validators as it would be a huge breaking change.

The touched i may be able to add.

**Comment by alexbouchardd** [comment] 2017-12-20 16:00
Thanks @joepuzzo appreciated!

**Comment by mihaiblaga89** [comment] 2017-12-20 17:12
@joepuzzo I'm talking about the values object from the submitError function

**Comment by mihaiblaga89** [comment] 2017-12-20 17:24
@joepuzzo I mean, for me it's pretty logic that "submitError" function that handles the validation, should know about not filled values. Coming back to my example from above, if I refresh the page and just click submit without filling anything, I get values = {} in submitError. How do you suggest I handle validations in this case?

**Closed** 2019-09-20 13:22 UTC
