### ISSUE TITLE
validation causes bad user experience

### ISSUE THREAD

**Issue by oxpa** [tannerlinsley/react-form#71] opened 2017-05-16 15:50 UTC
Hello.

In your demo: https://react-form.js.org/?selectedKind=2.%20Demos&selectedStory=Kitchen%20Sink&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel if an input changes it's state from 'valid' to 'invalid' a user action is prevented. 

1 click 'Email' radio button - it will be set up
2 click to 'City' input
3 click 'Text' radio button - an error for City will be display and radio button value is not changed
4 click 'Text' again - it will be chosen
5 click 'City' again and then 'Email' again - everything works as intended.

I think validation should not interrupt current user action (i.e. I should be able to select another radio button value despite the error in the City input)

**Comment by nickjohnson-dev** [comment] 2017-06-08 19:13
When trying to recreate this issue in the Storybook, I noticed that though the value indeed does not change on the radio button when first clicking outside the City input, this is merely due to the reflow of the page.

From what I can tell, because the reflow happens before your click event gets down to the radio button node, your click ends up clicking empty space on the page.

To prevent this from happening in a real-world app, you can reserve space for your error messages to prevent reflow.

**Comment by tannerlinsley** [comment] 2017-07-07 17:30
This is indeed caused by reflow. Closing :)

**Closed** 2017-07-07 17:30 UTC
